/*
 * generated by Xtext 2.20.0
 */
package fdit.dsl;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AttackScenarioRuntimeModule extends AbstractAttackScenarioRuntimeModule {

    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return AttackScenarioTerminalConverters.class;
    }
}
