/*
 * generated by Xtext 2.20.0
 */
package fdit.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AttackScenarioStandaloneSetup extends AttackScenarioStandaloneSetupGenerated {

	public static void doSetup() {
		new AttackScenarioStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
