/*
 * generated by Xtext 2.12.0
 */
package fdit.ltlcondition


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LTLConditionStandaloneSetup extends LTLConditionStandaloneSetupGenerated {

    def static void doSetup() {
        new LTLConditionStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
