/*
 * generated by Xtext 2.12.0
 */
package fdit.triggcondition


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TriggeringConditionStandaloneSetup extends TriggeringConditionStandaloneSetupGenerated {

    def static void doSetup() {
        new TriggeringConditionStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
