/*
 * generated by Xtext 2.12.0
 */
package fdit.triggcondition

import org.eclipse.xtext.conversion.IValueConverterService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TriggeringConditionRuntimeModule extends AbstractTriggeringConditionRuntimeModule {

    override Class<? extends IValueConverterService> bindIValueConverterService() {
        TriggeringConditionTerminalConverters
    }
}
