/*
 * generated by Xtext 2.20.0
 */
package fdit.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fdit.dsl.AttackScenarioRuntimeModule;
import fdit.dsl.AttackScenarioStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AttackScenarioIdeSetup extends AttackScenarioStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AttackScenarioRuntimeModule(), new AttackScenarioIdeModule()));
	}
	
}
