/*
 * generated by Xtext 2.12.0
 */
package fdit.dsl.ide


/**
 * Use this class to register ide components.
 */
class AttackScenarioGrammarIdeModule extends AbstractAttackScenarioGrammarIdeModule {
}
