/*
 * generated by Xtext 2.12.0
 */
package fdit.dsl.ide

import com.google.inject.Guice
import fdit.dsl.AttackScenarioGrammarRuntimeModule
import fdit.dsl.AttackScenarioGrammarStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AttackScenarioGrammarIdeSetup extends AttackScenarioGrammarStandaloneSetup {

    override createInjector() {
        Guice.createInjector(Modules2.mixin(new AttackScenarioGrammarRuntimeModule, new AttackScenarioGrammarIdeModule))
    }

}
